{
 "title": "Prometheus Benchmark",
 "description": "Reference: https://grafana.com/grafana/dashboards/12054-prometheus-benchmark-2-17-x/",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Prometheus",
    "query": {
     "query": "query_result(up{job=\"prometheus\"} == 1)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=\"prometheus\",pod=\"$pod\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "{{version}} - {{revision}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "Age"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Head Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "Time Series"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",type=\"float\",pod=\"$pod\"}[1m])",
     "legendFormat": "Samples/s"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Scrape Interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=\"prometheus\",pod=\"$pod\"}[1m]) /\nrate(prometheus_target_interval_length_seconds_count{job=\"prometheus\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Metadata Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_target_metadata_cache_bytes{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",pod=\"$pod\"}[1m])",
     "legendFormat": "Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",pod=\"$pod\"}[5m])",
     "legendFormat": "5m rate"
    },
    {
     "expr": "container_spec_cpu_quota{job=\"kubernetes-cadvisor\",container=\"prometheus\",node_name=~\".+-dup-0\",pod=\"$pod\"} /\ncontainer_spec_cpu_period{job=\"kubernetes-cadvisor\",container=\"prometheus\",node_name=~\".+-dup-0\",pod=\"$pod\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "container_spec_memory_limit_bytes{job=\"kubernetes-cadvisor\",container=\"prometheus\",node_name=~\".+-dup-0\",pod=\"$pod\"}",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}