{
 "title": "Federate Query",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "${VAR_NAMESPACE}" },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "query_result(up{job=~\"scrape-.*-metrics\"})"
    }
   },
   {
    "name": "pod",
    "label": "Prometheus",
    "query": {
     "query": "query_result(up{job=\"prometheus\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Scrape Conf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_interval_seconds{job=\"$target\"}) by(job)",
     "legendFormat": "Num"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_timeout_seconds{job=\"$target\"}) by(job)",
     "legendFormat": "Num"
    }
   ]
  },
  {
   "title": "Paralles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_paralles{job=\"$target\"}) by(job)",
     "legendFormat": "Num"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_upstream{job=\"$target\"}) by(path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Scrape Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Body Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_body_size_bytes{job=\"$target\"}) by(query)",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_lines{job=\"scrape-federate-metrics\"}) by(query)",
     "legendFormat": "{{query}}"
    },
    {
     "expr": "sum(federate_scrape_lines{job=\"scrape-federate-metrics\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(federate_scrape_duration{job=\"$target\"}) by(query,status_code)",
     "legendFormat": "{{query}}/{{status_code}}"
    },
    {
     "expr": "avg(federate_scrape_duration{job=\"$target\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "Prometheus Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Limits CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", service=\"kubelet\"}[30s])) by(namespace,pod,container)",
     "legendFormat": "Irate 30s"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", service=\"kubelet\"}[1m])) by(namespace,pod,container)",
     "legendFormat": "Irate 1m"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", service=\"kubelet\"}[5m])) by(namespace,pod,container)",
     "legendFormat": "Rate 5m"
    }
   ]
  },
  {
   "title": "Prometheus Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "WS"
    }
   ]
  },
  {
   "title": "Limits  Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\",  container=\"prometheus\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Limits CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"thanos-sidecar\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos-Sidecar CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"thanos-sidecar\", service=\"kubelet\"}[30s])) by(namespace,pod,container)",
     "legendFormat": "Irate 30s"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"thanos-sidecar\", service=\"kubelet\"}[1m])) by(namespace,pod,container)",
     "legendFormat": "Irate 1m"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"thanos-sidecar\", service=\"kubelet\"}[5m])) by(namespace,pod,container)",
     "legendFormat": "Rate 5m"
    }
   ]
  },
  {
   "title": "Thanos-Sidecar  Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container=\"thanos-sidecar\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"thanos-sidecar\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "WS"
    }
   ]
  },
  {
   "title": "Limits  Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\",  container=\"thanos-sidecar\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Thanos-Query Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Limits CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"thanos-query\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos-Query CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"thanos-query\", service=\"kubelet\"}[1m])) by(namespace,pod,container)",
     "legendFormat": "Irate 1m - {{pod}}"
    }
   ]
  },
  {
   "title": "Thanos-Query Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", container=\"thanos-query\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "RSS - {{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"thanos-query\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "WS - {{pod}}"
    }
   ]
  },
  {
   "title": "Limits  Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"thanos-query\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scraper Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Scraper CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$target-.*\", container=\"$target\", service=\"kubelet\"}[1m])) by(namespace,container)",
     "legendFormat": "Irate 1m"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$target-.*\", container=\"$target\", service=\"kubelet\"}[5m])) by(namespace,container)",
     "legendFormat": "Rate 5m"
    }
   ]
  },
  {
   "title": "Scraper Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=~\"$target-.*\", container=\"$target\",service=\"kubelet\"}) by(namespace,container)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$target-.*\", container=\"$target\",service=\"kubelet\"}) by(namespace,container)",
     "legendFormat": "WS"
    }
   ]
  }
 ]
}