{
 "title": "Prometheus Benchmark",
 "description": "Reference: https://grafana.com/grafana/dashboards/12054-prometheus-benchmark-2-17-x/",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "${VAR_NAMESPACE}" },
   {
    "name": "pod",
    "label": "Prometheus",
    "query": {
     "query": "query_result(up{job=\"prometheus\"} == 1)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=\"prometheus\",pod=\"$pod\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "non" } },
   "targets": [
    {
     "expr": "sum by(namespace, pod, container, version, revision) (prometheus_build_info{job=\"prometheus\", pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\",pod=\"$pod\"}",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}) by(namespace,pod,container)",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "title": "Limits - CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", resource=\"cpu\"}) by(namespace,pod,container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Limits - Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", resource=\"memory\"}) by(namespace,pod,container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Head Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=\"prometheus\", namespace=\"$namespace\", pod=\"$pod\"}) by(namespace,pod,container)",
     "legendFormat": "Time Series"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",type=\"float\",namespace=\"$namespace\",pod=\"$pod\"}[1m])) by(namespace,pod,container)",
     "legendFormat": "Samples/s"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Target Interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_interval_length_seconds{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\", quantile=\"0.99\"}) by(namespace,pod,container,interval) > 0",
     "legendFormat": " 99% - {{interval}}"
    },
    {
     "expr": "sum(prometheus_target_interval_length_seconds{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\", quantile=\"0.9\"}) by(namespace,pod,container,interval) > 0",
     "legendFormat": "90% - {{interval}}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}[30s])) by(namespace, pod, container)",
     "legendFormat": "Irate 30s"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}[1m])) by(namespace, pod, container)",
     "legendFormat": "Irate 1m "
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}[5m])) by(namespace, pod, container)",
     "legendFormat": "Rate 5m"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"prometheus\", pod=\"$pod\", service=\"kubelet\"}[5m])) by(namespace,pod,container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"prometheus\", pod=\"$pod\", service=\"kubelet\"}[5m])) by(namespace,pod,container)",
     "legendFormat": "Container CPU 5m rate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}) by(namespace,pod,container)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(go_memstats_next_gc_bytes{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}) by(namespace,pod,container)",
     "legendFormat": "Next GC"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"$namespace\",pod=\"$pod\"}) by(namespace,pod,container)",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\"}) by(namespace,pod,container)",
     "legendFormat": "Container - WS"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\"}) by(namespace,pod,container)",
     "legendFormat": "Container - RSS"
    }
   ]
  },
  {
   "title": "Container-CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", service=\"kubelet\"}[30s])) by(namespace,pod,container)",
     "legendFormat": "Irate 30s"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", service=\"kubelet\"}[1m])) by(namespace,pod,container)",
     "legendFormat": "Irate 1m"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\", service=\"kubelet\"}[5m])) by(namespace,pod,container)",
     "legendFormat": "Rate 5m"
    }
   ]
  },
  {
   "title": "Container-Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\",service=\"kubelet\"}) by(namespace,pod,container)",
     "legendFormat": "WS"
    }
   ]
  },
  { "title": "HEAD & WAL ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Head Chunks Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks_storage_size_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=\"prometheus\"}) by(namespace,pod,container)",
     "legendFormat": "Head Chunks"
    }
   ]
  },
  {
   "title": "WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_storage_size_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"prometheus\"}",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "Write Block",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_compaction_populating_block{namespace=\"$namespace\", pod=~\"$pod\", container=\"prometheus\"}) by(namespace,pod,container)",
     "legendFormat": "Writing"
    }
   ]
  },
  {
   "title": "Head Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_max_time{namespace=\"$namespace\", pod=~\"$pod\", container=\"prometheus\"} - prometheus_tsdb_head_min_time) by(namespace,pod,container)",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}